# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish release

on:
  workflow_call:
    inputs:
      target:
        description: "The git ref to checkout, build from and release"
        required: true
        type: string
      tag:
        description: "The tag of the release"
        required: true
        type: string
      prerelease:
        description: "Prerelease"
        required: false
        default: false
        type: boolean

env:
  CI_DIR: 2049ef39-42a2-46d2-b513-ee6d2e3a7b15
  RELEASES: |
    windows:client:Windows/Client
    windows:server:Windows/Server
    linux:client:Linux/Client
    linux:server:Linux/Server
    mac:client:Mac/Client/Barotrauma.app/Contents/MacOS
    mac:server:Mac/Server
  ARCHIVE_BASE_NAME: luacsforbarotrauma-${{ inputs.tag }}
  # XXX: these file names are subject to shell expansion.
  # Be careful when using special characters.
  ARCHIVE_FILES_SERVER: |
    DedicatedServer.deps.json
    DedicatedServer.dll
    DedicatedServer.pdb
    Publicized/DedicatedServer.dll
  ARCHIVE_FILES_CLIENT: |
    Barotrauma.deps.json
    Barotrauma.dll
    Barotrauma.pdb
    DedicatedServer.deps.json
    DedicatedServer.dll
    DedicatedServer.pdb
    Publicized/Barotrauma.dll
    Publicized/DedicatedServer.dll
  ARCHIVE_FILES_SHARED: |
    0Harmony.dll
    Sigil.dll
    MoonSharp.Interpreter.dll
    MoonSharp.VsCodeDebugger.dll
    MonoMod.Common.dll
    Mono.Cecil.dll
    Mono.Cecil.Mdb.dll
    Mono.Cecil.Pdb.dll
    Mono.Cecil.Rocks.dll
    Microsoft.CodeAnalysis.CSharp.Scripting.dll
    Microsoft.CodeAnalysis.CSharp.dll
    Microsoft.CodeAnalysis.dll
    Microsoft.CodeAnalysis.Scripting.dll
    System.Collections.Immutable.dll
    System.Reflection.Metadata.dll
    System.Runtime.CompilerServices.Unsafe.dll
    mscordaccore_amd64_amd64_*
    Lua
  BUILD_FILES: |
    .github/build_files/dummyitem.xml
    .github/build_files/filelist.xml
  FILE_TREE_SCHEME: .github/build_files/filetree.yml
  YQ_VERSION: v4.2.0
  YQ_BINARY: v4.2.0

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ inputs.target }}

  publish-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: |
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - |\
            tar xz && mv ${BINARY} /usr/bin/yq

      - name: Download build artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: build
          path: ${{ env.CI_DIR }}

      - name: Extract build artifacts
        run: |
          artifacts_dir="$(realpath -m "$CI_DIR/artifacts")"
          mkdir -p "$artifacts_dir"
          tar -xzf "$CI_DIR/build.tar.gz" -C "$artifacts_dir"
          rm "$CI_DIR/build.tar.gz"

      - name: Create archives
        run: |
          set -e
          shopt -s globstar nullglob
          shopt -u dotglob

          # This converts a newline-separated (LF) list into a Bash array
          # NOTE: this doesn't discard the trailing LF that GitHub actions
          # append (which results in an extra entry in the array).
          lines_to_array() {
            IFS=$'\n' readarray -td $'\n' "$1" <<< "${!1}"
          }




          lines_to_array ARCHIVE_FILES_SHARED
          lines_to_array ARCHIVE_FILES_CLIENT
          lines_to_array ARCHIVE_FILES_SERVER
          lines_to_array RELEASES
          lines_to_array BUILD_FILES

          if [ ! "$(command -v "yq")" ]; then
            echo "The required command \`yq' is not on the path or is not installed"
            exit 1;
          fi

          MOD_BUILD_FILES=$(yq eval '.Binary' "$CI_DIR/$FILE_TREE_SCHEME" | sed -E 's/- //gm')
          lines_to_array MOD_BUILD_FILES

          artifacts_dir="$(realpath -m "$CI_DIR/artifacts")"
          mkdir -p "$artifacts_dir"

          archives_dir="$(realpath -m "$CI_DIR/archives")"
          mkdir -p "$archives_dir"

          missing_build_files=""

          for i in "${!RELEASES[@]}"; do
            [[ -z "${RELEASES[i]}" ]] && continue
            (
              IFS=':' read -r platform side publish_dir _rest <<< "${RELEASES[i]}"
              cd "${artifacts_dir}/${publish_dir}"

              for key in "${MOD_BUILD_FILES[@]}"; do
                if [ ! -f "./${key}" ] && [ ! -d "./${key}" ]; then
                  missing_build_files="${missing_build_files}\n${key}";
                fi
              done

              if [ "${missing_build_files}" != "" ]; then
                echo "There were build files missing!"
                echo -e "${missing_build_files}"
                exit 1
              fi

              echo "Creating build_${platform}_${side}.zip"
              zip --must-match -qr "${archives_dir}/${ARCHIVE_BASE_NAME}_build_${platform}_${side}.zip" ./*

              echo "Creating build_${platform}_${side}.tar.gz"
              tar -czf "${archives_dir}/${ARCHIVE_BASE_NAME}_build_${platform}_${side}.tar.gz" \
                --owner=0 --group=0 \
                ./*

              if [[ "$side" == "client" ]]; then
                files=(
                  "${ARCHIVE_FILES_SHARED[@]}"
                  "${ARCHIVE_FILES_CLIENT[@]}"
                )
              elif [[ "$side" == "server" ]]; then
                files=(
                  "${ARCHIVE_FILES_SHARED[@]}"
                  "${ARCHIVE_FILES_SERVER[@]}"
                )
              else
                echo "Invalid side: $side"
                exit 1
              fi

              echo "Creating patch_${platform}_${side}.zip"
              zip \
                --must-match \
                -qr \
                "${archives_dir}/${ARCHIVE_BASE_NAME}_patch_${platform}_${side}.zip" \
                "${files[@]}"

              echo "Creating patch_${platform}_${side}.tar.gz"
              tar \
                -zcf "${archives_dir}/${ARCHIVE_BASE_NAME}_patch_${platform}_${side}.tar.gz" \
                --owner=0 --group=0 \
                "${files[@]}"

              echo "Creating mod_release_${platform}_${side}.zip"

              mkdir "${artifacts_dir}/${publish_dir}/global" \
                && mkdir "${artifacts_dir}/${publish_dir}/global/Binary" \
                  && cd "${artifacts_dir}/${publish_dir}/global/Binary" \
                    || exit 1

              for key in "${MOD_BUILD_FILES[@]}"; do
                cp -rfv "${artifacts_dir}/${publish_dir}/${key}" "${PWD}/${key}" \
                  || (echo "Failed to copy \`${artifacts_dir}/${publish_dir}/${key}' to \`${PWD}/${key}'" && exit 1)
              done

              cd "${artifacts_dir}/${publish_dir}/global"

              for key in "${BUILD_FILES[@]}"; do
                cp -rfv "${CI_DIR}/${key}" "${PWD}" \
                  || (echo "Failed to copy \`${CI_DIR}/${key}' to \`${PWD}/${key}'" && exit 1)
              done

              zip \
                --must-watch \
                -qr \
                "${archives_dir}/${ARCHIVE_BASE_NAME}_patch_${platform}_${side}.zip" \
                "./*"
            )
          done

      - name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: startsWith(github.event.head_commit.message, '[🧪]')
        with:
          path: |
            ${{ env.CI_DIR }}/archives/${{ env.ARCHIVE_BASE_NAME }}_{build,patch}_{windows,linux,mac}_{client,server}.zip
            ${{ env.CI_DIR }}/archives/${{ env.ARCHIVE_BASE_NAME }}_{build,patch}_linux_{client,server}.tar.gz
            ${{ env.CI_DIR }}/archives/mod_release_{windows,linux,mac}_global.zip

      - name: Publish release
        uses: notpeelz/action-gh-create-release@c1bebd17c8a128e8db4165a68be4dc4e3f106ff1 # v5.0.1
        if: "!startsWith(github.event.head_commit.message, '[🧪]')"
        with:
          target: ${{ inputs.target }}
          tag: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          strategy: replace
          title: "Automatic build"
          body: "Automatic build"
          files: |
            ${{ env.CI_DIR }}/archives/${{ env.ARCHIVE_BASE_NAME }}_{build,patch}_{windows,linux,mac}_{client,server}.zip
            ${{ env.CI_DIR }}/archives/${{ env.ARCHIVE_BASE_NAME }}_{build,patch}_linux_{client,server}.tar.gz
            ${{ env.CI_DIR }}/archives/mod_release_{windows,linux,mac}_global.zip
